import React, { useState, useRef, useEffect } from 'react';

interface SolanaWallet {
  address: string;
  balance: number;
  tokenHoldings: number;
  txCount: number;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  firstSeen: string;
  lastActive: string;
}

interface WhaleAlert {
  wallet: string;
  amount: number;
  token: string;
  direction: 'IN' | 'OUT';
  timestamp: string;
  txHash: string;
}

interface TokenAnalysis {
  name: string;
  symbol: string;
  mint: string;
  price: number;
  change24h: number;
  volume24h: number;
  marketCap: number;
  holders: number;
  liquidity: number;
  riskFlags: string[];
}

// Simulated on-chain intelligence engine
const solanaEngine = {
  analyzeWallet(address: string): SolanaWallet {
    const isBurned = address.startsWith('1111') || address.startsWith('0000');
    return {
      address,
      balance: isBurned ? 0 : Math.floor(Math.random() * 500) / 10,
      tokenHoldings: Math.floor(Math.random() * 25) + 1,
      txCount: Math.floor(Math.random() * 15000) + 50,
      riskLevel: (['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const)[Math.floor(Math.random() * 4)],
      firstSeen: '2023-06-' + String(Math.floor(Math.random() * 28) + 1).padStart(2, '0'),
      lastActive: new Date().toISOString().split('T')[0],
    };
  },

  getWhaleAlerts(): WhaleAlert[] {
    const wallets = ['So1ana...7aXk', 'Whale...9mPq', 'MEV...bOt4', 'JIT...sN4t', 'DeFi...fR8z'];
    const tokens = ['SOL', 'USDC', 'RAY', 'JTO', 'BONK', 'JUP', 'WIF'];
    return Array.from({ length: 8 }, (_, i) => ({
      wallet: wallets[Math.floor(Math.random() * wallets.length)],
      amount: Math.floor(Math.random() * 1000000) / 100,
      token: tokens[Math.floor(Math.random() * tokens.length)],
      direction: Math.random() > 0.5 ? 'IN' : 'OUT',
      timestamp: new Date(Date.now() - Math.random() * 3600000).toLocaleTimeString(),
      txHash: '5' + Array.from({ length: 87 }, () => '0123456789ABCDEF'[Math.floor(Math.random() * 16)]).join(''),
    }));
  },

  analyzeToken(mint: string): TokenAnalysis {
    const names = ['Jupiter Exchange', 'Marinade Finance', 'Raydium LP', 'Drift Protocol', 'Tensor NFT'];
    const symbols = ['JUP', 'MNDE', 'RAY-LP', 'DRIFT', 'TNSR'];
    const idx = Math.floor(Math.random() * names.length);
    const price = Math.floor(Math.random() * 50000) / 100;
    const flags = ['Low liquidity', 'High volatility', 'Rug pull risk', 'Honeypot detected', 'Locked vesting'];
    const numFlags = Math.floor(Math.random() * 3);
    return {
      name: names[idx],
      symbol: symbols[idx],
      mint,
      price,
      change24h: (Math.random() * 80 - 40).toFixed(2) as unknown as number,
      volume24h: Math.floor(Math.random() * 50000000) / 100,
      marketCap: price * (Math.floor(Math.random() * 100000000)),
      holders: Math.floor(Math.random() * 50000) + 100,
      liquidity: Math.floor(Math.random() * 10000000) / 100,
      riskFlags: Array.from({ length: numFlags }, (_, i) => flags[i]),
    };
  },

  traceTransaction(txHash: string): string[] {
    return [
      `[TRACE] Initiating TX analysis: ${txHash.substring(0, 16)}...`,
      `[SOLANA] Block: ${Math.floor(Math.random() * 250000000) + 200000000}`,
      `[SOLANA] Slot: ${Math.floor(Math.random() * 250000000) + 200000000}`,
      `[PARSE] Program: SystemProgram, TokenProgram, AssociatedTokenAccount`,
      `[TRACE] Pre-balances calculated for ${Math.floor(Math.random() * 4) + 2} accounts`,
      `[TRACE] Inner instructions: ${Math.floor(Math.random() * 15) + 1} found`,
      `[TRACE] Log messages: ${Math.floor(Math.random() * 25) + 5} parsed`,
      `[TRACE] Balance changes: SOL movement detected`,
      `[PARSE] Token transfers: ${(Math.random() * 3).toFixed(0)} token operations`,
      `[ANALYSIS] Transaction fee: 0.000005 SOL`,
      `[RESULT] Status: ${Math.random() > 0.1 ? 'SUCCESS' : 'FAILED'}`,
      `[RESULT] Compute units used: ${Math.floor(Math.random() * 200000) + 5000}`,
    ];
  },

  generateReport(data: { wallet?: SolanaWallet; token?: TokenAnalysis; txs?: string[] }): string {
    const lines = ['WHOAMISec Solana Intelligence Report', '====================================', `Generated: ${new Date().toISOString()}`, ''];
    if (data.wallet) {
      const w = data.wallet;
      lines.push(`WALLET: ${w.address}`, `Balance: ${w.balance} SOL`, `Risk: ${w.riskLevel}`, `Transactions: ${w.txCount}`, '');
    }
    if (data.token) {
      const t = data.token;
      lines.push(`TOKEN: ${t.name} (${t.symbol})`, `Price: $${t.price}`, `24h Change: ${t.change24h}%`, `Risk Flags: ${t.riskFlags.join(', ') || 'None'}`, '');
    }
    lines.push('---', 'Report generated by WHOAMISec Solana Chain Explorer V2.0');
    return lines.join('\n');
  }
};

export default function SolanaTool() {
  const [activeTab, setActiveTab] = useState<'wallet' | 'whales' | 'token' | 'trace'>('wallet');
  const [walletInput, setWalletInput] = useState('');
  const [tokenInput, setTokenInput] = useState('');
  const [txInput, setTxInput] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [logs, setLogs] = useState<string[]>([
    '[INIT] Solana Chain Explorer V2.0 initialized.',
    '[RPC] Connected to WHOAMISec Solana Intelligence Node.',
    '[READY] Awaiting target wallet, token, or transaction hash...'
  ]);
  const [walletData, setWalletData] = useState<SolanaWallet | null>(null);
  const [whaleAlerts, setWhaleAlerts] = useState<WhaleAlert[]>([]);
  const [tokenData, setTokenData] = useState<TokenAnalysis | null>(null);
  const [txLogs, setTxLogs] = useState<string[]>([]);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [logs, txLogs]);

  const addLog = (msg: string, level: 'info' | 'success' | 'error' | 'warning' = 'info') => {
    const ts = new Date().toLocaleTimeString();
    const pfx = level === 'success' ? '[+]' : level === 'error' ? '[!]' : level === 'warning' ? '[*]' : '[_]';
    setLogs(prev => [...prev.slice(-100), `${ts} ${pfx} ${msg}`]);
  };

  const analyzeWallet = () => {
    if (!walletInput) return;
    setIsProcessing(true);
    setWalletData(null);
    addLog(`Analyzing wallet: ${walletInput.substring(0, 16)}...`, 'warning');
    setTimeout(() => {
      const data = solanaEngine.analyzeWallet(walletInput);
      setWalletData(data);
      addLog(`Wallet analysis complete. Risk: ${data.riskLevel}`, data.riskLevel === 'CRITICAL' || data.riskLevel === 'HIGH' ? 'error' : 'success');
      setIsProcessing(false);
    }, 1500);
  };

  const refreshWhales = () => {
    setIsProcessing(true);
    addLog('Fetching whale movement data from WHOAMISec Intel Node...', 'warning');
    setTimeout(() => {
      const alerts = solanaEngine.getWhaleAlerts();
      setWhaleAlerts(alerts);
      addLog(`${alerts.length} whale movements detected in last hour.`, 'success');
      setIsProcessing(false);
    }, 1200);
  };

  const analyzeToken = () => {
    if (!tokenInput) return;
    setIsProcessing(true);
    setTokenData(null);
    addLog(`Analyzing token mint: ${tokenInput.substring(0, 16)}...`, 'warning');
    setTimeout(() => {
      const data = solanaEngine.analyzeToken(tokenInput);
      setTokenData(data);
      addLog(`Token ${data.symbol} analysis complete. Price: $${data.price}`, 'success');
      if (data.riskFlags.length > 0) {
        data.riskFlags.forEach(f => addLog(`RISK FLAG: ${f}`, 'error'));
      }
      setIsProcessing(false);
    }, 1800);
  };

  const traceTx = () => {
    if (!txInput) return;
    setIsProcessing(true);
    setTxLogs([]);
    addLog(`Tracing transaction: ${txInput.substring(0, 16)}...`, 'warning');
    const traceLines = solanaEngine.traceTransaction(txInput);
    traceLines.forEach((line, i) => {
      setTimeout(() => {
        setTxLogs(prev => [...prev, line]);
        if (i === traceLines.length - 1) {
          setIsProcessing(false);
          addLog('Transaction trace complete.', 'success');
        }
      }, (i + 1) * 300);
    });
  };

  const exportReport = () => {
    const report = solanaEngine.generateReport({ wallet: walletData, token: tokenData, txs: txLogs });
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `solana_report_${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
    addLog('Report exported.', 'success');
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'CRITICAL': return 'text-red-500 bg-red-500/10 border-red-500/30';
      case 'HIGH': return 'text-orange-500 bg-orange-500/10 border-orange-500/30';
      case 'MEDIUM': return 'text-yellow-500 bg-yellow-500/10 border-yellow-500/30';
      default: return 'text-emerald-500 bg-emerald-500/10 border-emerald-500/30';
    }
  };

  const tabs = [
    { id: 'wallet' as const, label: 'Wallet', icon: 'fa-wallet' },
    { id: 'whales' as const, label: 'Whales', icon: 'fa-water' },
    { id: 'token' as const, label: 'Token', icon: 'fa-coins' },
    { id: 'trace' as const, label: 'TX Trace', icon: 'fa-route' },
  ];

  return (
    <div className="p-4 space-y-4 bg-black border border-purple-900/30 rounded-lg">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-black text-purple-400 uppercase tracking-tighter">
          <i className="fab fa-react mr-2"></i>SOLANA CHAIN EXPLORER
        </h2>
        <div className="flex gap-2">
          <button onClick={exportReport} className="px-2 py-1 bg-blue-600/20 border border-blue-600 text-blue-400 text-xs rounded hover:bg-blue-600/30">
            <i className="fas fa-download mr-1"></i>Export
          </button>
          <button onClick={() => { setLogs([]); setWalletData(null); setTokenData(null); setWhaleAlerts([]); setTxLogs([]); }} className="px-2 py-1 bg-red-600/20 border border-red-600 text-red-400 text-xs rounded hover:bg-red-600/30">
            <i className="fas fa-trash mr-1"></i>Clear
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-black/40 border border-purple-900/20 rounded p-1">
        {tabs.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            className={`flex-1 py-1.5 text-xs font-black uppercase rounded transition-all ${activeTab === tab.id ? 'bg-purple-600 text-white' : 'text-gray-500 hover:text-gray-300'}`}>
            <i className={`fas ${tab.icon} mr-1`}></i>{tab.label}
          </button>
        ))}
      </div>

      {/* Wallet Tab */}
      {activeTab === 'wallet' && (
        <div className="space-y-3">
          <div className="bg-black/40 border border-purple-900/20 rounded p-3">
            <label className="text-purple-400 text-xs font-black uppercase block mb-2">
              <i className="fas fa-crosshairs mr-1"></i>Wallet Address
            </label>
            <input type="text" value={walletInput} onChange={e => setWalletInput(e.target.value)}
              placeholder="Enter Solana wallet address..."
              className="w-full bg-black border border-purple-900/30 rounded px-3 py-2 text-purple-400 font-mono text-sm outline-none focus:border-purple-500/50" />
            <button onClick={analyzeWallet} disabled={isProcessing || !walletInput}
              className="mt-2 w-full py-2 bg-purple-600 hover:bg-purple-500 text-white text-xs font-black uppercase rounded transition-all disabled:opacity-50">
              {isProcessing ? <><i className="fas fa-spinner fa-spin mr-1"></i>Analyzing...</> : <><i className="fas fa-search mr-1"></i>Analyze Wallet</>}
            </button>
          </div>
          {walletData && (
            <div className="bg-black/40 border border-purple-900/20 rounded p-3 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-purple-400 font-bold text-xs">Wallet Intelligence</span>
                <span className={`px-2 py-0.5 rounded text-xs font-bold border ${getRiskColor(walletData.riskLevel)}`}>
                  RISK: {walletData.riskLevel}
                </span>
              </div>
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Balance</span>
                  <span className="text-purple-300 font-bold">{walletData.balance} SOL</span>
                </div>
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Token Holdings</span>
                  <span className="text-purple-300 font-bold">{walletData.tokenHoldings}</span>
                </div>
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Transactions</span>
                  <span className="text-purple-300 font-bold">{walletData.txCount.toLocaleString()}</span>
                </div>
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">First Active</span>
                  <span className="text-purple-300 font-bold">{walletData.firstSeen}</span>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Whales Tab */}
      {activeTab === 'whales' && (
        <div className="space-y-3">
          <button onClick={refreshWhales} disabled={isProcessing}
            className="w-full py-2 bg-purple-600 hover:bg-purple-500 text-white text-xs font-black uppercase rounded transition-all disabled:opacity-50">
            {isProcessing ? <><i className="fas fa-spinner fa-spin mr-1"></i>Fetching...</> : <><i className="fas fa-water mr-1"></i>Refresh Whale Alerts</>}
          </button>
          {whaleAlerts.length > 0 && (
            <div className="space-y-2 max-h-80 overflow-y-auto">
              {whaleAlerts.map((alert, i) => (
                <div key={i} className={`bg-black/60 border rounded p-2 ${alert.direction === 'IN' ? 'border-emerald-900/20' : 'border-red-900/20'}`}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-purple-400 font-bold text-xs">{alert.wallet}</span>
                    <span className={`px-2 py-0.5 rounded text-xs font-bold ${alert.direction === 'IN' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                      {alert.direction} {alert.amount.toLocaleString()} {alert.token}
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-500">{alert.timestamp} | TX: {alert.txHash.substring(0, 16)}...</div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Token Tab */}
      {activeTab === 'token' && (
        <div className="space-y-3">
          <div className="bg-black/40 border border-purple-900/20 rounded p-3">
            <label className="text-purple-400 text-xs font-black uppercase block mb-2">
              <i className="fas fa-coins mr-1"></i>Token Mint Address
            </label>
            <input type="text" value={tokenInput} onChange={e => setTokenInput(e.target.value)}
              placeholder="Enter token mint address..."
              className="w-full bg-black border border-purple-900/30 rounded px-3 py-2 text-purple-400 font-mono text-sm outline-none focus:border-purple-500/50" />
            <button onClick={analyzeToken} disabled={isProcessing || !tokenInput}
              className="mt-2 w-full py-2 bg-purple-600 hover:bg-purple-500 text-white text-xs font-black uppercase rounded transition-all disabled:opacity-50">
              {isProcessing ? <><i className="fas fa-spinner fa-spin mr-1"></i>Analyzing...</> : <><i className="fas fa-chart-line mr-1"></i>Analyze Token</>}
            </button>
          </div>
          {tokenData && (
            <div className="bg-black/40 border border-purple-900/20 rounded p-3 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-purple-400 font-bold text-xs">{tokenData.name} ({tokenData.symbol})</span>
                <span className={`px-2 py-0.5 rounded text-xs font-bold ${Number(tokenData.change24h) >= 0 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                  {Number(tokenData.change24h) >= 0 ? '+' : ''}{tokenData.change24h}%
                </span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-xs">
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Price</span>
                  <span className="text-purple-300 font-bold">${tokenData.price}</span>
                </div>
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Volume 24h</span>
                  <span className="text-purple-300 font-bold">${(tokenData.volume24h / 1000000).toFixed(2)}M</span>
                </div>
                <div className="bg-black/60 border border-purple-900/10 rounded p-2">
                  <span className="text-gray-500 block">Holders</span>
                  <span className="text-purple-300 font-bold">{tokenData.holders.toLocaleString()}</span>
                </div>
              </div>
              {tokenData.riskFlags.length > 0 && (
                <div>
                  <span className="text-red-400 text-xs font-bold">Risk Flags:</span>
                  <div className="flex flex-wrap gap-1 mt-1">
                    {tokenData.riskFlags.map((f, i) => (
                      <span key={i} className="px-2 py-0.5 bg-red-500/10 border border-red-500/30 text-red-400 text-[10px] rounded">{f}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* TX Trace Tab */}
      {activeTab === 'trace' && (
        <div className="space-y-3">
          <div className="bg-black/40 border border-purple-900/20 rounded p-3">
            <label className="text-purple-400 text-xs font-black uppercase block mb-2">
              <i className="fas fa-route mr-1"></i>Transaction Signature
            </label>
            <input type="text" value={txInput} onChange={e => setTxInput(e.target.value)}
              placeholder="Enter transaction hash..."
              className="w-full bg-black border border-purple-900/30 rounded px-3 py-2 text-purple-400 font-mono text-sm outline-none focus:border-purple-500/50" />
            <button onClick={traceTx} disabled={isProcessing || !txInput}
              className="mt-2 w-full py-2 bg-purple-600 hover:bg-purple-500 text-white text-xs font-black uppercase rounded transition-all disabled:opacity-50">
              {isProcessing ? <><i className="fas fa-spinner fa-spin mr-1"></i>Tracing...</> : <><i className="fas fa-search mr-1"></i>Trace Transaction</>}
            </button>
          </div>
          {txLogs.length > 0 && (
            <div className="bg-black/60 border border-purple-900/10 rounded p-2 h-64 overflow-y-auto font-mono text-xs">
              {txLogs.map((line, i) => (
                <div key={i} className={line.includes('[RESULT]') ? 'text-purple-400 font-bold' : line.includes('[!]') ? 'text-red-400' : 'text-gray-400'}>
                  {line}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* System Logs */}
      <div className="bg-black/40 border border-purple-900/20 rounded p-3">
        <label className="text-purple-400 text-xs font-black uppercase block mb-2">
          <i className="fas fa-terminal mr-1"></i>System Logs
        </label>
        <div ref={messagesEndRef} className="bg-black/60 border border-purple-900/10 rounded p-2 h-28 overflow-y-auto font-mono text-xs text-gray-400">
          {logs.map((log, i) => <div key={i}>{log}</div>)}
        </div>
      </div>
    </div>
  );
}
